# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CShaper.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(837, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Function = QtWidgets.QTabWidget(self.centralwidget)
        self.Function.setGeometry(QtCore.QRect(40, 30, 791, 551))
        self.Function.setObjectName("Function")
        self.Preprocess = QtWidgets.QWidget()
        self.Preprocess.setObjectName("Preprocess")
        self.label = QtWidgets.QLabel(self.Preprocess)
        self.label.setGeometry(QtCore.QRect(40, 20, 371, 31))
        self.label.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.Preprocess)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 80, 281, 331))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.xYResolutionLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.xYResolutionLabel.setObjectName("xYResolutionLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.xYResolutionLabel)
        self.LE_xyResolution = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LE_xyResolution.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.LE_xyResolution.setPlaceholderText("")
        self.LE_xyResolution.setObjectName("LE_xyResolution")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LE_xyResolution)
        self.zResolutionLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.zResolutionLabel.setObjectName("zResolutionLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.zResolutionLabel)
        self.LE_zResolution = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LE_zResolution.setPlaceholderText("")
        self.LE_zResolution.setObjectName("LE_zResolution")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LE_zResolution)
        self.xYZSizeLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.xYZSizeLabel.setObjectName("xYZSizeLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.xYZSizeLabel)
        self.LE_reduceRatio = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LE_reduceRatio.setPlaceholderText("")
        self.LE_reduceRatio.setObjectName("LE_reduceRatio")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LE_reduceRatio)
        self.sliceNumLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.sliceNumLabel.setObjectName("sliceNumLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.sliceNumLabel)
        self.LE_sliceNum = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LE_sliceNum.setPlaceholderText("")
        self.LE_sliceNum.setObjectName("LE_sliceNum")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LE_sliceNum)
        self.tPNumLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.tPNumLabel.setObjectName("tPNumLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.tPNumLabel)
        self.LE_maxTime = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LE_maxTime.setPlaceholderText("")
        self.LE_maxTime.setObjectName("LE_maxTime")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.LE_maxTime)
        self.nucleusFolderLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.nucleusFolderLabel.setObjectName("nucleusFolderLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.nucleusFolderLabel)
        self.LE_stackFolder = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LE_stackFolder.setText("")
        self.LE_stackFolder.setObjectName("LE_stackFolder")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.LE_stackFolder)
        self.membraneFolderLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.membraneFolderLabel.setObjectName("membraneFolderLabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.membraneFolderLabel)
        self.LE_lineage = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LE_lineage.setObjectName("LE_lineage")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.LE_lineage)
        self.stackFolderLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.stackFolderLabel_2.setObjectName("stackFolderLabel_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.stackFolderLabel_2)
        self.LE_rawFolder = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LE_rawFolder.setObjectName("LE_rawFolder")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LE_rawFolder)
        self.embryoNamesLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.embryoNamesLabel.setObjectName("embryoNamesLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.embryoNamesLabel)
        self.CB_embryoNames = QtWidgets.QComboBox(self.formLayoutWidget)
        self.CB_embryoNames.setObjectName("CB_embryoNames")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.CB_embryoNames)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.LE_shapeFile = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LE_shapeFile.setObjectName("LE_shapeFile")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.LE_shapeFile)
        self.label_2 = QtWidgets.QLabel(self.Preprocess)
        self.label_2.setGeometry(QtCore.QRect(330, 140, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Preprocess)
        self.label_3.setGeometry(QtCore.QRect(330, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Btn_runPreprocess = QtWidgets.QPushButton(self.Preprocess)
        self.Btn_runPreprocess.setGeometry(QtCore.QRect(470, 190, 131, 51))
        self.Btn_runPreprocess.setObjectName("Btn_runPreprocess")
        self.Btn_lineageFile = QtWidgets.QPushButton(self.Preprocess)
        self.Btn_lineageFile.setGeometry(QtCore.QRect(330, 280, 77, 23))
        self.Btn_lineageFile.setObjectName("Btn_lineageFile")
        self.Btn_rawFolder = QtWidgets.QPushButton(self.Preprocess)
        self.Btn_rawFolder.setGeometry(QtCore.QRect(330, 80, 77, 23))
        self.Btn_rawFolder.setObjectName("Btn_rawFolder")
        self.Btn_stackFolder = QtWidgets.QPushButton(self.Preprocess)
        self.Btn_stackFolder.setGeometry(QtCore.QRect(330, 250, 77, 23))
        self.Btn_stackFolder.setObjectName("Btn_stackFolder")
        self.Btn_shapeFile = QtWidgets.QPushButton(self.Preprocess)
        self.Btn_shapeFile.setGeometry(QtCore.QRect(330, 310, 77, 23))
        self.Btn_shapeFile.setObjectName("Btn_shapeFile")
        self.Function.addTab(self.Preprocess, "")
        self.Segmentation = QtWidgets.QWidget()
        self.Segmentation.setObjectName("Segmentation")
        self.label_5 = QtWidgets.QLabel(self.Segmentation)
        self.label_5.setGeometry(QtCore.QRect(40, 20, 371, 31))
        self.label_5.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.Segmentation)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(40, 60, 281, 321))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.embryoNameLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.embryoNameLabel.setObjectName("embryoNameLabel")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.embryoNameLabel)
        self.maxTPLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.maxTPLabel.setObjectName("maxTPLabel")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.maxTPLabel)
        self.LE_maxTime_Seg = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LE_maxTime_Seg.setObjectName("LE_maxTime_Seg")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LE_maxTime_Seg)
        self.saveFolderLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.saveFolderLabel.setObjectName("saveFolderLabel")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.saveFolderLabel)
        self.LE_saveFolder_Seg = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LE_saveFolder_Seg.setObjectName("LE_saveFolder_Seg")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.LE_saveFolder_Seg)
        self.useLineageLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.useLineageLabel.setObjectName("useLineageLabel")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.useLineageLabel)
        self.CB_lineage_Seg = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.CB_lineage_Seg.setObjectName("CB_lineage_Seg")
        self.CB_lineage_Seg.addItem("")
        self.CB_lineage_Seg.addItem("")
        self.CB_lineage_Seg.addItem("")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.CB_lineage_Seg)
        self.CB_embryoNames_Seg = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.CB_embryoNames_Seg.setObjectName("CB_embryoNames_Seg")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.CB_embryoNames_Seg)
        self.dataFolderLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.dataFolderLabel.setObjectName("dataFolderLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.dataFolderLabel)
        self.LE_stackFolder_Seg = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LE_stackFolder_Seg.setObjectName("LE_stackFolder_Seg")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LE_stackFolder_Seg)
        self.batchSizeLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.batchSizeLabel.setObjectName("batchSizeLabel")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.batchSizeLabel)
        self.LE_batchSize_Seg = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LE_batchSize_Seg.setObjectName("LE_batchSize_Seg")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LE_batchSize_Seg)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.LE_modelFile_Seg = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LE_modelFile_Seg.setObjectName("LE_modelFile_Seg")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.LE_modelFile_Seg)
        self.Btn_stackFolder_Seg = QtWidgets.QPushButton(self.Segmentation)
        self.Btn_stackFolder_Seg.setGeometry(QtCore.QRect(330, 80, 81, 23))
        self.Btn_stackFolder_Seg.setObjectName("Btn_stackFolder_Seg")
        self.Btn_runSegmentation = QtWidgets.QPushButton(self.Segmentation)
        self.Btn_runSegmentation.setGeometry(QtCore.QRect(470, 130, 131, 51))
        self.Btn_runSegmentation.setStyleSheet("")
        self.Btn_runSegmentation.setObjectName("Btn_runSegmentation")
        self.Btn_saveFolder_Seg = QtWidgets.QPushButton(self.Segmentation)
        self.Btn_saveFolder_Seg.setGeometry(QtCore.QRect(330, 190, 81, 23))
        self.Btn_saveFolder_Seg.setObjectName("Btn_saveFolder_Seg")
        self.Btn_modelFile_Seg = QtWidgets.QPushButton(self.Segmentation)
        self.Btn_modelFile_Seg.setGeometry(QtCore.QRect(330, 240, 81, 23))
        self.Btn_modelFile_Seg.setObjectName("Btn_modelFile_Seg")
        self.Function.addTab(self.Segmentation, "")
        self.Analysis = QtWidgets.QWidget()
        self.Analysis.setObjectName("Analysis")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.Analysis)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(40, 90, 281, 281))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.sliceNumLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.sliceNumLabel_2.setObjectName("sliceNumLabel_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sliceNumLabel_2)
        self.stackFolderLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.stackFolderLabel.setObjectName("stackFolderLabel")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.stackFolderLabel)
        self.LE_stackFolder_Ana = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LE_stackFolder_Ana.setObjectName("LE_stackFolder_Ana")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LE_stackFolder_Ana)
        self.LE_sliceNum_Ana = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LE_sliceNum_Ana.setObjectName("LE_sliceNum_Ana")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LE_sliceNum_Ana)
        self.LE_xyResolution_Ana = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LE_xyResolution_Ana.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.LE_xyResolution_Ana.setPlaceholderText("")
        self.LE_xyResolution_Ana.setObjectName("LE_xyResolution_Ana")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LE_xyResolution_Ana)
        self.xYResolutionLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.xYResolutionLabel_2.setObjectName("xYResolutionLabel_2")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.xYResolutionLabel_2)
        self.LE_rawFolder_Ana = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LE_rawFolder_Ana.setObjectName("LE_rawFolder_Ana")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LE_rawFolder_Ana)
        self.rawFolderLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.rawFolderLabel.setObjectName("rawFolderLabel")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.rawFolderLabel)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.LE_shapeUtil_Ana = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LE_shapeUtil_Ana.setObjectName("LE_shapeUtil_Ana")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LE_shapeUtil_Ana)
        self.CB_embryoNames_Ana = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.CB_embryoNames_Ana.setObjectName("CB_embryoNames_Ana")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.CB_embryoNames_Ana)
        self.embryoNameLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.embryoNameLabel_2.setObjectName("embryoNameLabel_2")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.embryoNameLabel_2)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.LE_saveFolder_Ana = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.LE_saveFolder_Ana.setObjectName("LE_saveFolder_Ana")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.LE_saveFolder_Ana)
        self.label_6 = QtWidgets.QLabel(self.Analysis)
        self.label_6.setGeometry(QtCore.QRect(40, 20, 371, 31))
        self.label_6.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.Btn_runAnalysis = QtWidgets.QPushButton(self.Analysis)
        self.Btn_runAnalysis.setGeometry(QtCore.QRect(470, 130, 131, 51))
        self.Btn_runAnalysis.setObjectName("Btn_runAnalysis")
        self.Btn_runAll = QtWidgets.QPushButton(self.Analysis)
        self.Btn_runAll.setGeometry(QtCore.QRect(410, 260, 261, 51))
        self.Btn_runAll.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.Btn_runAll.setObjectName("Btn_runAll")
        self.checkBox = QtWidgets.QCheckBox(self.Analysis)
        self.checkBox.setGeometry(QtCore.QRect(40, 70, 70, 17))
        self.checkBox.setObjectName("checkBox")
        self.Btn_rawFolder_Ana = QtWidgets.QPushButton(self.Analysis)
        self.Btn_rawFolder_Ana.setGeometry(QtCore.QRect(330, 150, 81, 23))
        self.Btn_rawFolder_Ana.setObjectName("Btn_rawFolder_Ana")
        self.Btn_stackFolder_Ana = QtWidgets.QPushButton(self.Analysis)
        self.Btn_stackFolder_Ana.setGeometry(QtCore.QRect(330, 190, 81, 23))
        self.Btn_stackFolder_Ana.setObjectName("Btn_stackFolder_Ana")
        self.Btn_shapeUtil_Ana = QtWidgets.QPushButton(self.Analysis)
        self.Btn_shapeUtil_Ana.setGeometry(QtCore.QRect(330, 110, 81, 23))
        self.Btn_shapeUtil_Ana.setObjectName("Btn_shapeUtil_Ana")
        self.Btn_saveFolder_Ana = QtWidgets.QPushButton(self.Analysis)
        self.Btn_saveFolder_Ana.setGeometry(QtCore.QRect(330, 240, 81, 23))
        self.Btn_saveFolder_Ana.setObjectName("Btn_saveFolder_Ana")
        self.Function.addTab(self.Analysis, "")
        self.Result = QtWidgets.QWidget()
        self.Result.setObjectName("Result")
        self.label_7 = QtWidgets.QLabel(self.Result)
        self.label_7.setGeometry(QtCore.QRect(210, 10, 371, 31))
        self.label_7.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.tabWidget = QtWidgets.QTabWidget(self.Result)
        self.tabWidget.setGeometry(QtCore.QRect(20, 80, 761, 441))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView_3 = QtWidgets.QTableView(self.tab)
        self.tableView_3.setGeometry(QtCore.QRect(0, 0, 761, 411))
        self.tableView_3.setObjectName("tableView_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableView_2 = QtWidgets.QTableView(self.tab_2)
        self.tableView_2.setGeometry(QtCore.QRect(0, 0, 761, 411))
        self.tableView_2.setObjectName("tableView_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableView = QtWidgets.QTableView(self.tab_3)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 761, 411))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab_3, "")
        self.Function.addTab(self.Result, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 837, 23))
        self.menubar.setObjectName("menubar")
        self.menuNew_Project = QtWidgets.QMenu(self.menubar)
        self.menuNew_Project.setObjectName("menuNew_Project")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionLoad_Project = QtWidgets.QAction(MainWindow)
        self.actionLoad_Project.setObjectName("actionLoad_Project")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionOnline_Document = QtWidgets.QAction(MainWindow)
        self.actionOnline_Document.setObjectName("actionOnline_Document")
        self.actionCopy_Right = QtWidgets.QAction(MainWindow)
        self.actionCopy_Right.setObjectName("actionCopy_Right")
        self.actionRun_Preprocess = QtWidgets.QAction(MainWindow)
        self.actionRun_Preprocess.setObjectName("actionRun_Preprocess")
        self.actionRun_Segmentation = QtWidgets.QAction(MainWindow)
        self.actionRun_Segmentation.setObjectName("actionRun_Segmentation")
        self.actionRun_Analysis = QtWidgets.QAction(MainWindow)
        self.actionRun_Analysis.setObjectName("actionRun_Analysis")
        self.actionOpen_Project_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project_Folder.setObjectName("actionOpen_Project_Folder")
        self.actionRun_ALL = QtWidgets.QAction(MainWindow)
        self.actionRun_ALL.setObjectName("actionRun_ALL")
        self.menuNew_Project.addAction(self.actionNew_Project)
        self.menuNew_Project.addAction(self.actionLoad_Project)
        self.menuNew_Project.addAction(self.actionOpen_Project_Folder)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuAbout.addAction(self.actionVersion)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionOnline_Document)
        self.menuAbout.addAction(self.actionCopy_Right)
        self.menuRun.addAction(self.actionRun_Preprocess)
        self.menuRun.addAction(self.actionRun_Segmentation)
        self.menuRun.addAction(self.actionRun_Analysis)
        self.menuRun.addAction(self.actionRun_ALL)
        self.menubar.addAction(self.menuNew_Project.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.Function.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Experimental Information"))
        self.xYResolutionLabel.setText(_translate("MainWindow", "X-Y Resolution:"))
        self.zResolutionLabel.setText(_translate("MainWindow", "Z Resolution:"))
        self.xYZSizeLabel.setText(_translate("MainWindow", "Reduce Ratio"))
        self.sliceNumLabel.setText(_translate("MainWindow", "Slice Num:"))
        self.tPNumLabel.setText(_translate("MainWindow", "Max Time:"))
        self.nucleusFolderLabel.setText(_translate("MainWindow", "Stack Folder:"))
        self.membraneFolderLabel.setText(_translate("MainWindow", "Lineage File:"))
        self.stackFolderLabel_2.setText(_translate("MainWindow", "Raw Folder:"))
        self.embryoNamesLabel.setText(_translate("MainWindow", "Embryo Names:"))
        self.label_4.setText(_translate("MainWindow", "Shape File:"))
        self.label_2.setText(_translate("MainWindow", "um"))
        self.label_3.setText(_translate("MainWindow", "um"))
        self.Btn_runPreprocess.setText(_translate("MainWindow", "Run Preprocess"))
        self.Btn_lineageFile.setText(_translate("MainWindow", "Lineage"))
        self.Btn_rawFolder.setText(_translate("MainWindow", "Raw"))
        self.Btn_stackFolder.setText(_translate("MainWindow", "Stack"))
        self.Btn_shapeFile.setText(_translate("MainWindow", "Shape"))
        self.Function.setTabText(self.Function.indexOf(self.Preprocess), _translate("MainWindow", "Preprocess"))
        self.label_5.setText(_translate("MainWindow", "Segmentation Parameters"))
        self.embryoNameLabel.setText(_translate("MainWindow", "Embryo Names:"))
        self.maxTPLabel.setText(_translate("MainWindow", "Max Time:"))
        self.LE_maxTime_Seg.setPlaceholderText(_translate("MainWindow", "Max time points to be segmented"))
        self.saveFolderLabel.setText(_translate("MainWindow", "Save Folder:"))
        self.LE_saveFolder_Seg.setPlaceholderText(_translate("MainWindow", "Choose result folder"))
        self.useLineageLabel.setText(_translate("MainWindow", "Use Lineage?"))
        self.CB_lineage_Seg.setItemText(0, _translate("MainWindow", "No lineage"))
        self.CB_lineage_Seg.setItemText(1, _translate("MainWindow", "Before segmentation"))
        self.CB_lineage_Seg.setItemText(2, _translate("MainWindow", "After segmentation"))
        self.dataFolderLabel.setText(_translate("MainWindow", "Stack Folder:"))
        self.LE_stackFolder_Seg.setPlaceholderText(_translate("MainWindow", "Choose raw image folder"))
        self.batchSizeLabel.setText(_translate("MainWindow", "Batch Size:"))
        self.label_8.setText(_translate("MainWindow", "Model File:"))
        self.Btn_stackFolder_Seg.setText(_translate("MainWindow", "Stack"))
        self.Btn_runSegmentation.setText(_translate("MainWindow", "Run Segmentation"))
        self.Btn_saveFolder_Seg.setText(_translate("MainWindow", "Save"))
        self.Btn_modelFile_Seg.setText(_translate("MainWindow", "Model"))
        self.Function.setTabText(self.Function.indexOf(self.Segmentation), _translate("MainWindow", "Segmentation"))
        self.sliceNumLabel_2.setText(_translate("MainWindow", "Slice Num"))
        self.stackFolderLabel.setText(_translate("MainWindow", "Stack Folder"))
        self.xYResolutionLabel_2.setText(_translate("MainWindow", "X-Y Resolution:"))
        self.rawFolderLabel.setText(_translate("MainWindow", "Raw Folder"))
        self.label_9.setText(_translate("MainWindow", "ShapeUtil"))
        self.embryoNameLabel_2.setText(_translate("MainWindow", "Embryo Name:"))
        self.label_10.setText(_translate("MainWindow", "Save Folder"))
        self.label_6.setText(_translate("MainWindow", "Analysis Parameters"))
        self.Btn_runAnalysis.setText(_translate("MainWindow", "Run Analysis"))
        self.Btn_runAll.setText(_translate("MainWindow", "Run Preprocess, Segmentation and Analysis"))
        self.checkBox.setText(_translate("MainWindow", "Initial run"))
        self.Btn_rawFolder_Ana.setText(_translate("MainWindow", "Raw"))
        self.Btn_stackFolder_Ana.setText(_translate("MainWindow", "Stack"))
        self.Btn_shapeUtil_Ana.setText(_translate("MainWindow", "Shape"))
        self.Btn_saveFolder_Ana.setText(_translate("MainWindow", "Save"))
        self.Function.setTabText(self.Function.indexOf(self.Analysis), _translate("MainWindow", "Analysis"))
        self.label_7.setText(_translate("MainWindow", "Show Stastical Result"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Surface"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Volume"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Contact Surface"))
        self.Function.setTabText(self.Function.indexOf(self.Result), _translate("MainWindow", "Result"))
        self.menuNew_Project.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))
        self.actionLoad_Project.setText(_translate("MainWindow", "Load Project"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionVersion.setText(_translate("MainWindow", "Version"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionOnline_Document.setText(_translate("MainWindow", "Online Document"))
        self.actionCopy_Right.setText(_translate("MainWindow", "Copy Right"))
        self.actionRun_Preprocess.setText(_translate("MainWindow", "Run Preprocess"))
        self.actionRun_Segmentation.setText(_translate("MainWindow", "Run Segmentation"))
        self.actionRun_Analysis.setText(_translate("MainWindow", "Run Analysis"))
        self.actionOpen_Project_Folder.setText(_translate("MainWindow", "Open Project Folder"))
        self.actionRun_ALL.setText(_translate("MainWindow", "Run ALL !"))
