# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CShaper.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Function = QtWidgets.QTabWidget(self.centralwidget)
        self.Function.setGeometry(QtCore.QRect(0, 0, 791, 551))
        self.Function.setObjectName("Function")
        self.Preprocess = QtWidgets.QWidget()
        self.Preprocess.setObjectName("Preprocess")
        self.label = QtWidgets.QLabel(self.Preprocess)
        self.label.setGeometry(QtCore.QRect(40, 20, 371, 31))
        self.label.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.PreprogressBar = QtWidgets.QProgressBar(self.Preprocess)
        self.PreprogressBar.setGeometry(QtCore.QRect(270, 500, 501, 20))
        self.PreprogressBar.setProperty("value", 0)
        self.PreprogressBar.setInvertedAppearance(False)
        self.PreprogressBar.setObjectName("PreprogressBar")
        self.label_Preprocess = QtWidgets.QLabel(self.Preprocess)
        self.label_Preprocess.setGeometry(QtCore.QRect(10, 500, 251, 20))
        self.label_Preprocess.setText("")
        self.label_Preprocess.setObjectName("label_Preprocess")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.Preprocess)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(40, 70, 371, 327))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.zResolutionLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.zResolutionLabel.setObjectName("zResolutionLabel")
        self.gridLayout_4.addWidget(self.zResolutionLabel, 3, 0, 1, 1)
        self.LE_lineage = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.LE_lineage.setObjectName("LE_lineage")
        self.gridLayout_4.addWidget(self.LE_lineage, 8, 1, 1, 1)
        self.stackFolderLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.stackFolderLabel_2.setObjectName("stackFolderLabel_2")
        self.gridLayout_4.addWidget(self.stackFolderLabel_2, 0, 0, 1, 1)
        self.embryoNamesLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.embryoNamesLabel.setObjectName("embryoNamesLabel")
        self.gridLayout_4.addWidget(self.embryoNamesLabel, 1, 0, 1, 1)
        self.LE_rawFolder = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.LE_rawFolder.setObjectName("LE_rawFolder")
        self.gridLayout_4.addWidget(self.LE_rawFolder, 0, 1, 1, 1)
        self.LE_xyResolution = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.LE_xyResolution.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.LE_xyResolution.setPlaceholderText("")
        self.LE_xyResolution.setObjectName("LE_xyResolution")
        self.gridLayout_4.addWidget(self.LE_xyResolution, 2, 1, 1, 1)
        self.LE_sliceNum = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.LE_sliceNum.setPlaceholderText("")
        self.LE_sliceNum.setObjectName("LE_sliceNum")
        self.gridLayout_4.addWidget(self.LE_sliceNum, 5, 1, 1, 1)
        self.LE_maxTime = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.LE_maxTime.setPlaceholderText("")
        self.LE_maxTime.setObjectName("LE_maxTime")
        self.gridLayout_4.addWidget(self.LE_maxTime, 6, 1, 1, 1)
        self.LE_zResolution = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.LE_zResolution.setPlaceholderText("")
        self.LE_zResolution.setObjectName("LE_zResolution")
        self.gridLayout_4.addWidget(self.LE_zResolution, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 3, 2, 1, 1)
        self.tPNumLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.tPNumLabel.setObjectName("tPNumLabel")
        self.gridLayout_4.addWidget(self.tPNumLabel, 6, 0, 1, 1)
        self.sliceNumLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.sliceNumLabel.setObjectName("sliceNumLabel")
        self.gridLayout_4.addWidget(self.sliceNumLabel, 5, 0, 1, 1)
        self.nucleusFolderLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.nucleusFolderLabel.setObjectName("nucleusFolderLabel")
        self.gridLayout_4.addWidget(self.nucleusFolderLabel, 7, 0, 1, 1)
        self.membraneFolderLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.membraneFolderLabel.setObjectName("membraneFolderLabel")
        self.gridLayout_4.addWidget(self.membraneFolderLabel, 8, 0, 1, 1)
        self.xYResolutionLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.xYResolutionLabel.setObjectName("xYResolutionLabel")
        self.gridLayout_4.addWidget(self.xYResolutionLabel, 2, 0, 1, 1)
        self.Btn_lineageFile = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.Btn_lineageFile.setObjectName("Btn_lineageFile")
        self.gridLayout_4.addWidget(self.Btn_lineageFile, 8, 2, 1, 1)
        self.CB_embryoNames = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.CB_embryoNames.setObjectName("CB_embryoNames")
        self.gridLayout_4.addWidget(self.CB_embryoNames, 1, 1, 1, 1)
        self.LE_projectFolder = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.LE_projectFolder.setText("")
        self.LE_projectFolder.setObjectName("LE_projectFolder")
        self.gridLayout_4.addWidget(self.LE_projectFolder, 7, 1, 1, 1)
        self.LE_reduceRatio = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.LE_reduceRatio.setPlaceholderText("")
        self.LE_reduceRatio.setObjectName("LE_reduceRatio")
        self.gridLayout_4.addWidget(self.LE_reduceRatio, 4, 1, 1, 1)
        self.Btn_projectFolder = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.Btn_projectFolder.setObjectName("Btn_projectFolder")
        self.gridLayout_4.addWidget(self.Btn_projectFolder, 7, 2, 1, 1)
        self.xYZSizeLabel = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.xYZSizeLabel.setObjectName("xYZSizeLabel")
        self.gridLayout_4.addWidget(self.xYZSizeLabel, 4, 0, 1, 1)
        self.Btn_rawFolder = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.Btn_rawFolder.setObjectName("Btn_rawFolder")
        self.gridLayout_4.addWidget(self.Btn_rawFolder, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 9, 0, 1, 1)
        self.LE_numberDict = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.LE_numberDict.setObjectName("LE_numberDict")
        self.gridLayout_4.addWidget(self.LE_numberDict, 9, 1, 1, 1)
        self.Btn_numberDict = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.Btn_numberDict.setObjectName("Btn_numberDict")
        self.gridLayout_4.addWidget(self.Btn_numberDict, 9, 2, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Preprocess)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(510, 190, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Btn_runPreprocess = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_runPreprocess.setObjectName("Btn_runPreprocess")
        self.verticalLayout.addWidget(self.Btn_runPreprocess)
        self.Btn_stopPreprocess = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Btn_stopPreprocess.setObjectName("Btn_stopPreprocess")
        self.verticalLayout.addWidget(self.Btn_stopPreprocess)
        self.Function.addTab(self.Preprocess, "")
        self.Segmentation = QtWidgets.QWidget()
        self.Segmentation.setObjectName("Segmentation")
        self.label_5 = QtWidgets.QLabel(self.Segmentation)
        self.label_5.setGeometry(QtCore.QRect(40, 20, 371, 31))
        self.label_5.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Segmentation)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 70, 372, 201))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.embryoNameLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.embryoNameLabel.setObjectName("embryoNameLabel")
        self.gridLayout_2.addWidget(self.embryoNameLabel, 1, 0, 1, 1)
        self.CB_embryoNames_Seg = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.CB_embryoNames_Seg.setObjectName("CB_embryoNames_Seg")
        self.gridLayout_2.addWidget(self.CB_embryoNames_Seg, 1, 1, 1, 1)
        self.CB_lineage_Seg = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.CB_lineage_Seg.setObjectName("CB_lineage_Seg")
        self.CB_lineage_Seg.addItem("")
        self.CB_lineage_Seg.addItem("")
        self.CB_lineage_Seg.addItem("")
        self.gridLayout_2.addWidget(self.CB_lineage_Seg, 4, 1, 1, 1)
        self.useLineageLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.useLineageLabel.setObjectName("useLineageLabel")
        self.gridLayout_2.addWidget(self.useLineageLabel, 4, 0, 1, 1)
        self.maxTPLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.maxTPLabel.setObjectName("maxTPLabel")
        self.gridLayout_2.addWidget(self.maxTPLabel, 2, 0, 1, 1)
        self.LE_maxTime_Seg = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.LE_maxTime_Seg.setObjectName("LE_maxTime_Seg")
        self.gridLayout_2.addWidget(self.LE_maxTime_Seg, 2, 1, 1, 1)
        self.batchSizeLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.batchSizeLabel.setObjectName("batchSizeLabel")
        self.gridLayout_2.addWidget(self.batchSizeLabel, 3, 0, 1, 1)
        self.LE_batchSize_Seg = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.LE_batchSize_Seg.setObjectName("LE_batchSize_Seg")
        self.gridLayout_2.addWidget(self.LE_batchSize_Seg, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 1)
        self.LE_modelFile_Seg = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.LE_modelFile_Seg.setObjectName("LE_modelFile_Seg")
        self.gridLayout_2.addWidget(self.LE_modelFile_Seg, 5, 1, 1, 1)
        self.Btn_modelFile_Seg = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Btn_modelFile_Seg.setObjectName("Btn_modelFile_Seg")
        self.gridLayout_2.addWidget(self.Btn_modelFile_Seg, 5, 2, 1, 1)
        self.Btn_projectFolder_Seg = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Btn_projectFolder_Seg.setObjectName("Btn_projectFolder_Seg")
        self.gridLayout_2.addWidget(self.Btn_projectFolder_Seg, 0, 2, 1, 1)
        self.LE_projectFolder_Seg = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.LE_projectFolder_Seg.setObjectName("LE_projectFolder_Seg")
        self.gridLayout_2.addWidget(self.LE_projectFolder_Seg, 0, 1, 1, 1)
        self.dataFolderLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.dataFolderLabel.setObjectName("dataFolderLabel")
        self.gridLayout_2.addWidget(self.dataFolderLabel, 0, 0, 1, 1)
        self.SegmentationBar = QtWidgets.QProgressBar(self.Segmentation)
        self.SegmentationBar.setGeometry(QtCore.QRect(270, 500, 501, 20))
        self.SegmentationBar.setProperty("value", 0)
        self.SegmentationBar.setInvertedAppearance(False)
        self.SegmentationBar.setObjectName("SegmentationBar")
        self.label_Segmentation = QtWidgets.QLabel(self.Segmentation)
        self.label_Segmentation.setGeometry(QtCore.QRect(10, 500, 251, 20))
        self.label_Segmentation.setText("")
        self.label_Segmentation.setObjectName("label_Segmentation")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Segmentation)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(510, 110, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_runSegmentation = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Btn_runSegmentation.setStyleSheet("")
        self.Btn_runSegmentation.setObjectName("Btn_runSegmentation")
        self.verticalLayout_2.addWidget(self.Btn_runSegmentation)
        self.Btn_stopSegmentation = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Btn_stopSegmentation.setObjectName("Btn_stopSegmentation")
        self.verticalLayout_2.addWidget(self.Btn_stopSegmentation)
        self.Function.addTab(self.Segmentation, "")
        self.Analysis = QtWidgets.QWidget()
        self.Analysis.setObjectName("Analysis")
        self.label_6 = QtWidgets.QLabel(self.Analysis)
        self.label_6.setGeometry(QtCore.QRect(40, 20, 371, 31))
        self.label_6.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.checkBox = QtWidgets.QCheckBox(self.Analysis)
        self.checkBox.setGeometry(QtCore.QRect(40, 60, 161, 17))
        self.checkBox.setObjectName("checkBox")
        self.AnalysisBar = QtWidgets.QProgressBar(self.Analysis)
        self.AnalysisBar.setGeometry(QtCore.QRect(270, 500, 501, 20))
        self.AnalysisBar.setProperty("value", 0)
        self.AnalysisBar.setInvertedAppearance(False)
        self.AnalysisBar.setObjectName("AnalysisBar")
        self.label_Analysis = QtWidgets.QLabel(self.Analysis)
        self.label_Analysis.setGeometry(QtCore.QRect(10, 500, 251, 20))
        self.label_Analysis.setText("")
        self.label_Analysis.setObjectName("label_Analysis")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.Analysis)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(40, 80, 371, 235))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rawFolderLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.rawFolderLabel.setObjectName("rawFolderLabel")
        self.gridLayout_3.addWidget(self.rawFolderLabel, 3, 0, 1, 1)
        self.xYResolutionLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.xYResolutionLabel_2.setObjectName("xYResolutionLabel_2")
        self.gridLayout_3.addWidget(self.xYResolutionLabel_2, 1, 0, 1, 1)
        self.LE_sliceNum_Ana = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.LE_sliceNum_Ana.setEnabled(True)
        self.LE_sliceNum_Ana.setObjectName("LE_sliceNum_Ana")
        self.gridLayout_3.addWidget(self.LE_sliceNum_Ana, 0, 1, 1, 1)
        self.stackFolderLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.stackFolderLabel.setObjectName("stackFolderLabel")
        self.gridLayout_3.addWidget(self.stackFolderLabel, 5, 0, 1, 1)
        self.LE_projectFolder_Ana = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.LE_projectFolder_Ana.setObjectName("LE_projectFolder_Ana")
        self.gridLayout_3.addWidget(self.LE_projectFolder_Ana, 5, 1, 1, 1)
        self.embryoNameLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.embryoNameLabel_2.setObjectName("embryoNameLabel_2")
        self.gridLayout_3.addWidget(self.embryoNameLabel_2, 4, 0, 1, 1)
        self.LE_rawFolder_Ana = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.LE_rawFolder_Ana.setObjectName("LE_rawFolder_Ana")
        self.gridLayout_3.addWidget(self.LE_rawFolder_Ana, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.LE_numberDict_Ana = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.LE_numberDict_Ana.setObjectName("LE_numberDict_Ana")
        self.gridLayout_3.addWidget(self.LE_numberDict_Ana, 2, 1, 1, 1)
        self.LE_xyResolution_Ana = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.LE_xyResolution_Ana.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.LE_xyResolution_Ana.setPlaceholderText("")
        self.LE_xyResolution_Ana.setObjectName("LE_xyResolution_Ana")
        self.gridLayout_3.addWidget(self.LE_xyResolution_Ana, 1, 1, 1, 1)
        self.Btn_numberDict_Ana = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.Btn_numberDict_Ana.setObjectName("Btn_numberDict_Ana")
        self.gridLayout_3.addWidget(self.Btn_numberDict_Ana, 2, 2, 1, 1)
        self.sliceNumLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.sliceNumLabel_2.setObjectName("sliceNumLabel_2")
        self.gridLayout_3.addWidget(self.sliceNumLabel_2, 0, 0, 1, 1)
        self.CB_embryoNames_Ana = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.CB_embryoNames_Ana.setObjectName("CB_embryoNames_Ana")
        self.gridLayout_3.addWidget(self.CB_embryoNames_Ana, 4, 1, 1, 1)
        self.Btn_projectFolder_Ana = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.Btn_projectFolder_Ana.setObjectName("Btn_projectFolder_Ana")
        self.gridLayout_3.addWidget(self.Btn_projectFolder_Ana, 5, 2, 1, 1)
        self.Btn_rawFolder_Ana = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.Btn_rawFolder_Ana.setObjectName("Btn_rawFolder_Ana")
        self.gridLayout_3.addWidget(self.Btn_rawFolder_Ana, 3, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 6, 0, 1, 1)
        self.LE_lineage_Ana = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.LE_lineage_Ana.setObjectName("LE_lineage_Ana")
        self.gridLayout_3.addWidget(self.LE_lineage_Ana, 6, 1, 1, 1)
        self.Btn_lineageFile_Ana = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.Btn_lineageFile_Ana.setObjectName("Btn_lineageFile_Ana")
        self.gridLayout_3.addWidget(self.Btn_lineageFile_Ana, 6, 2, 1, 1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.Analysis)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(510, 120, 160, 124))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Btn_runAnalysis = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.Btn_runAnalysis.setObjectName("Btn_runAnalysis")
        self.verticalLayout_3.addWidget(self.Btn_runAnalysis)
        self.Btn_stopAnalysis = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.Btn_stopAnalysis.setObjectName("Btn_stopAnalysis")
        self.verticalLayout_3.addWidget(self.Btn_stopAnalysis)
        self.Btn_runAll = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.Btn_runAll.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.Btn_runAll.setObjectName("Btn_runAll")
        self.verticalLayout_3.addWidget(self.Btn_runAll)
        self.Function.addTab(self.Analysis, "")
        self.Result = QtWidgets.QWidget()
        self.Result.setObjectName("Result")
        self.label_7 = QtWidgets.QLabel(self.Result)
        self.label_7.setGeometry(QtCore.QRect(210, 10, 371, 31))
        self.label_7.setStyleSheet("background-color: rgb(173, 173, 173);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.tabWidget = QtWidgets.QTabWidget(self.Result)
        self.tabWidget.setGeometry(QtCore.QRect(10, 70, 761, 441))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView_3 = QtWidgets.QTableView(self.tab)
        self.tableView_3.setGeometry(QtCore.QRect(0, 0, 761, 421))
        self.tableView_3.setObjectName("tableView_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableView_2 = QtWidgets.QTableView(self.tab_2)
        self.tableView_2.setGeometry(QtCore.QRect(0, 0, 761, 411))
        self.tableView_2.setObjectName("tableView_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableView = QtWidgets.QTableView(self.tab_3)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 761, 411))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 721, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Slider_3d = QtWidgets.QSlider(self.tab_4)
        self.Slider_3d.setGeometry(QtCore.QRect(730, 10, 22, 391))
        self.Slider_3d.setOrientation(QtCore.Qt.Vertical)
        self.Slider_3d.setObjectName("Slider_3d")
        self.tabWidget.addTab(self.tab_4, "")
        self.Label_idx = QtWidgets.QLabel(self.Result)
        self.Label_idx.setGeometry(QtCore.QRect(660, 40, 111, 31))
        self.Label_idx.setText("")
        self.Label_idx.setObjectName("Label_idx")
        self.Function.addTab(self.Result, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 24))
        self.menubar.setObjectName("menubar")
        self.menuNew_Project = QtWidgets.QMenu(self.menubar)
        self.menuNew_Project.setObjectName("menuNew_Project")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionLoad_Project = QtWidgets.QAction(MainWindow)
        self.actionLoad_Project.setObjectName("actionLoad_Project")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionOnline_Document = QtWidgets.QAction(MainWindow)
        self.actionOnline_Document.setObjectName("actionOnline_Document")
        self.actionCopy_Right = QtWidgets.QAction(MainWindow)
        self.actionCopy_Right.setObjectName("actionCopy_Right")
        self.actionRun_Preprocess = QtWidgets.QAction(MainWindow)
        self.actionRun_Preprocess.setObjectName("actionRun_Preprocess")
        self.actionRun_Segmentation = QtWidgets.QAction(MainWindow)
        self.actionRun_Segmentation.setObjectName("actionRun_Segmentation")
        self.actionRun_Analysis = QtWidgets.QAction(MainWindow)
        self.actionRun_Analysis.setObjectName("actionRun_Analysis")
        self.actionOpen_Project_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project_Folder.setObjectName("actionOpen_Project_Folder")
        self.actionRun_ALL = QtWidgets.QAction(MainWindow)
        self.actionRun_ALL.setObjectName("actionRun_ALL")
        self.actionSave_Project = QtWidgets.QAction(MainWindow)
        self.actionSave_Project.setObjectName("actionSave_Project")
        self.actionOpen_Result_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Result_Folder.setObjectName("actionOpen_Result_Folder")
        self.menuNew_Project.addAction(self.actionNew_Project)
        self.menuNew_Project.addAction(self.actionSave_Project)
        self.menuNew_Project.addAction(self.actionLoad_Project)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuAbout.addAction(self.actionVersion)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionCopy_Right)
        self.menuRun.addAction(self.actionRun_Preprocess)
        self.menuRun.addAction(self.actionRun_Segmentation)
        self.menuRun.addAction(self.actionRun_Analysis)
        self.menuRun.addAction(self.actionRun_ALL)
        self.menuRun.addAction(self.actionOpen_Result_Folder)
        self.menubar.addAction(self.menuNew_Project.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.Function.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Experimental Information"))
        self.PreprogressBar.setFormat(_translate("MainWindow", "%p%"))
        self.zResolutionLabel.setText(_translate("MainWindow", "Z Resolution:"))
        self.stackFolderLabel_2.setText(_translate("MainWindow", "Raw Folder:"))
        self.embryoNamesLabel.setText(_translate("MainWindow", "Embryo Names:"))
        self.label_3.setText(_translate("MainWindow", "um"))
        self.tPNumLabel.setText(_translate("MainWindow", "Max Time:"))
        self.sliceNumLabel.setText(_translate("MainWindow", "Slice Num:"))
        self.nucleusFolderLabel.setText(_translate("MainWindow", "Project Folder:"))
        self.membraneFolderLabel.setText(_translate("MainWindow", "Lineage File:"))
        self.xYResolutionLabel.setText(_translate("MainWindow", "X-Y Resolution:"))
        self.Btn_lineageFile.setText(_translate("MainWindow", "Choose"))
        self.Btn_projectFolder.setText(_translate("MainWindow", "Choose"))
        self.xYZSizeLabel.setText(_translate("MainWindow", "Reduce Ratio"))
        self.Btn_rawFolder.setText(_translate("MainWindow", "Choose"))
        self.label_2.setText(_translate("MainWindow", "um"))
        self.label_4.setText(_translate("MainWindow", "Number dictionary:"))
        self.Btn_numberDict.setText(_translate("MainWindow", "Choose"))
        self.Btn_runPreprocess.setText(_translate("MainWindow", "Run Preprocess"))
        self.Btn_stopPreprocess.setText(_translate("MainWindow", "Stop Preprocess"))
        self.Function.setTabText(self.Function.indexOf(self.Preprocess), _translate("MainWindow", "Preprocess"))
        self.label_5.setText(_translate("MainWindow", "Segmentation Parameters"))
        self.embryoNameLabel.setText(_translate("MainWindow", "Embryo Names:"))
        self.CB_lineage_Seg.setItemText(0, _translate("MainWindow", "No lineage"))
        self.CB_lineage_Seg.setItemText(1, _translate("MainWindow", "Before segmentation"))
        self.CB_lineage_Seg.setItemText(2, _translate("MainWindow", "After segmentation"))
        self.useLineageLabel.setText(_translate("MainWindow", "Use Lineage?"))
        self.maxTPLabel.setText(_translate("MainWindow", "Max Time:"))
        self.LE_maxTime_Seg.setPlaceholderText(_translate("MainWindow", "Max time points to be segmented"))
        self.batchSizeLabel.setText(_translate("MainWindow", "Batch Size:"))
        self.label_8.setText(_translate("MainWindow", "Model File:"))
        self.Btn_modelFile_Seg.setText(_translate("MainWindow", "Choose"))
        self.Btn_projectFolder_Seg.setText(_translate("MainWindow", "Choose"))
        self.LE_projectFolder_Seg.setPlaceholderText(_translate("MainWindow", "Choose raw image folder"))
        self.dataFolderLabel.setText(_translate("MainWindow", "Project Folder:"))
        self.SegmentationBar.setFormat(_translate("MainWindow", "%p%"))
        self.Btn_runSegmentation.setText(_translate("MainWindow", "Run Segmentation"))
        self.Btn_stopSegmentation.setText(_translate("MainWindow", "Stop Segmentation"))
        self.Function.setTabText(self.Function.indexOf(self.Segmentation), _translate("MainWindow", "Segmentation"))
        self.label_6.setText(_translate("MainWindow", "Analysis Parameters"))
        self.checkBox.setText(_translate("MainWindow", "Initial run"))
        self.AnalysisBar.setFormat(_translate("MainWindow", "%p%"))
        self.rawFolderLabel.setText(_translate("MainWindow", "Raw Folder"))
        self.xYResolutionLabel_2.setText(_translate("MainWindow", "X-Y Resolution:"))
        self.stackFolderLabel.setText(_translate("MainWindow", "Project Folder"))
        self.embryoNameLabel_2.setText(_translate("MainWindow", "Embryo Name:"))
        self.label_9.setText(_translate("MainWindow", "Number Dictionary:"))
        self.Btn_numberDict_Ana.setText(_translate("MainWindow", "Choose"))
        self.sliceNumLabel_2.setText(_translate("MainWindow", "Slice Num"))
        self.Btn_projectFolder_Ana.setText(_translate("MainWindow", "Choose"))
        self.Btn_rawFolder_Ana.setText(_translate("MainWindow", "Choose"))
        self.label_10.setText(_translate("MainWindow", "Lineage File:"))
        self.Btn_lineageFile_Ana.setText(_translate("MainWindow", "Choose"))
        self.Btn_runAnalysis.setText(_translate("MainWindow", "Run Analysis"))
        self.Btn_stopAnalysis.setText(_translate("MainWindow", "Stop Analysis"))
        self.Btn_runAll.setText(_translate("MainWindow", "Run Preprocess, \n"
"Segmentation \n"
"and Analysis"))
        self.Function.setTabText(self.Function.indexOf(self.Analysis), _translate("MainWindow", "Analysis"))
        self.label_7.setText(_translate("MainWindow", "Show Statistical Result"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Surface"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Volume"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Contact Surface"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "3D"))
        self.Function.setTabText(self.Function.indexOf(self.Result), _translate("MainWindow", "Result"))
        self.menuNew_Project.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project"))
        self.actionLoad_Project.setText(_translate("MainWindow", "Load Project"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionVersion.setText(_translate("MainWindow", "Version"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionOnline_Document.setText(_translate("MainWindow", "Online Document"))
        self.actionCopy_Right.setText(_translate("MainWindow", "Copy Right"))
        self.actionRun_Preprocess.setText(_translate("MainWindow", "Run Preprocess"))
        self.actionRun_Segmentation.setText(_translate("MainWindow", "Run Segmentation"))
        self.actionRun_Analysis.setText(_translate("MainWindow", "Run Analysis"))
        self.actionOpen_Project_Folder.setText(_translate("MainWindow", "Open Project Folder"))
        self.actionRun_ALL.setText(_translate("MainWindow", "Run ALL !"))
        self.actionSave_Project.setText(_translate("MainWindow", "Save Project"))
        self.actionOpen_Result_Folder.setText(_translate("MainWindow", "Open Result Folder"))

